services:
  app:
    build: .
    container_name: knowledgebase-ai

    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - hf_cache:/root/.cache/huggingface

volumes:
  hf_cache: